import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Next Notebook",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  const locale = (await params).locale

  // Ensure that the incoming `locale` is valid
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="antialiased">
        <NextIntlClientProvider messages={messages}>
          <Sidebar />
          <div className="ml-[260px]">
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html >
  );
}
