import type { Metadata } from "next";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import Header from "@/components/header";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Next Notebook",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const locale = (await params).locale

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            {/* <Sidebar />
          <div className="ml-[260px]">
            {children}
          </div> */}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
